/* Atlas: nouvelle scène spatiale. On déplace le monde entier, pas les images seules. */
(()=>{'use strict';const ui=window.ExperienceUI,world=document.getElementById('atlas-world'),windowEl=document.getElementById('atlas-window'),journey=document.getElementById('atlas-journey'),leaves=[...world.children];let ctx,score,trigger,places=[],current='puerta',layout=null;
if(!window.gsap||!window.ScrollTrigger){document.body.classList.add('static');return}gsap.registerPlugin(ScrollTrigger);
function compose(){document.body.classList.remove('static');document.body.classList.add('animated');places=[];ctx=gsap.context(()=>{
layout=()=>leaves.forEach(l=>gsap.set(l,{left:Number(l.dataset.x)*innerWidth,top:Number(l.dataset.y)*windowEl.clientHeight}));layout();ScrollTrigger.addEventListener('refreshInit',layout);gsap.set(world,{x:0,y:0});score=gsap.timeline({paused:true,defaults:{ease:'power2.inOut'}});let t=0;
leaves.forEach((l,i)=>{const q=s=>l.querySelector(s),all=s=>l.querySelectorAll(s);const duration=[2.5,2.6,2.7,2.9,2.5,3.4,2.7,2.8][i];places.push({id:l.id,start:t});score.addLabel(l.id,t+1);
if(i===0){score.fromTo(q('.door-photo'),{clipPath:'inset(100% 0% 0% 0%)'},{clipPath:'inset(0% 0% 0% 0%)',duration:1.2},t);const path=q('.door-drawing path');const length=path.getTotalLength();score.fromTo(path,{strokeDasharray:length,strokeDashoffset:length},{strokeDashoffset:0,duration:1.5},t);score.fromTo(q('.door-words'),{autoAlpha:0,x:35},{autoAlpha:1,x:0,duration:.7},t+.75)}
if(i===1){score.fromTo(q('.stone-pan img'),{scale:1.2,xPercent:5},{scale:1.08,xPercent:-3,duration:2.5,ease:'sine.inOut'},t);score.fromTo(q('.stone-detail'),{autoAlpha:0,y:-80,rotation:3},{autoAlpha:1,y:0,rotation:0,duration:.8},t+.6);score.fromTo(q('.stone-caption'),{autoAlpha:0,y:25},{autoAlpha:1,y:0,duration:.6},t+1.35)}
if(i===2){score.fromTo(q('.plaza-wide'),{clipPath:'inset(0% 50% 0% 50%)'},{clipPath:'inset(0% 0% 0% 0%)',duration:1},t);score.fromTo(all('.voices-words span'),{autoAlpha:0,y:20},{autoAlpha:1,y:0,stagger:.3,duration:.4},t+.75);score.fromTo(q('.voices-detail'),{y:70,autoAlpha:0},{y:0,autoAlpha:1,duration:.75},t+1.1)}
if(i===3){score.fromTo(q('.hour-face'),{scale:.25,autoAlpha:0},{scale:1,autoAlpha:1,duration:1.1},t+.3);score.to(q('.hour-building'),{autoAlpha:.08,duration:1},t+.3);score.fromTo(q('.hour-lines'),{rotation:-50},{rotation:30,duration:2.8,ease:'none'},t);score.fromTo(q('h2'),{autoAlpha:0,y:30},{autoAlpha:1,y:0,duration:.7},t+1.1)}
if(i===4){score.fromTo(q('.breath-photo img'),{scale:1.15},{scale:1,duration:2.5,ease:'sine.inOut'},t);score.fromTo(all('.breath-rings i'),{scale:.6,autoAlpha:0},{scale:1.1,autoAlpha:.5,stagger:.2,duration:1.5,ease:'sine.out'},t+.25);score.fromTo(q('.breath-note'),{autoAlpha:0},{autoAlpha:1,duration:1},t+1)}
if(i===5){score.fromTo(q('.height-image'),{yPercent:95,autoAlpha:0},{yPercent:0,autoAlpha:1,duration:1.2},t+.2);score.to(q('h2'),{autoAlpha:0,y:-30,duration:.5},t+.45);score.to(q('.height-image'),{xPercent:-25,scale:.6,autoAlpha:.3,duration:.8},t+1.7);score.fromTo(q('.height-detail'),{clipPath:'inset(0% 0% 100% 0%)'},{clipPath:'inset(0% 0% 0% 0%)',duration:.85},t+1.75);score.fromTo(q('.height-note'),{autoAlpha:0},{autoAlpha:1,duration:.6},t+2.2)}
if(i===6){score.fromTo(q('.interval-photo'),{clipPath:'inset(0% 100% 0% 0%)'},{clipPath:'inset(0% 0% 0% 0%)',duration:1.3},t+.1);const p=q('.interval-line path'),length=p.getTotalLength();score.fromTo(p,{strokeDasharray:length,strokeDashoffset:length},{strokeDashoffset:0,duration:1.4,ease:'none'},t);score.to(q('.interval-line'),{autoAlpha:0,duration:.5},t+1.5);score.fromTo(q('h2 em'),{x:-60,autoAlpha:0},{x:0,autoAlpha:1,duration:.75},t+.6)}
if(i===7){score.fromTo(q('.echo-photo'),{scale:1.15,autoAlpha:0},{scale:1,autoAlpha:1,duration:1.3},t);score.fromTo(q('h2'),{autoAlpha:0,y:25},{autoAlpha:1,y:0,duration:.9},t+.45);score.fromTo(all('.echo-rings i'),{scale:.5},{scale:1.2,duration:2.5,stagger:.1,ease:'sine.out'},t+.2)}
t+=duration+.45;
if(i<leaves.length-1){const next=leaves[i+1],travel=i===3?1.9:1.55; // Horizontal ou vertical: la page suivante est réellement adjacente.
score.to(world,{x:()=>-Number(next.dataset.x)*innerWidth,y:()=>-Number(next.dataset.y)*windowEl.clientHeight,duration:travel,ease:i===4?'sine.inOut':'power2.inOut'},t);
// Une respiration d'échelle ponctue le passage: les deux pages restent visibles.
if(i===1||i===3){score.to(l,{scale:.94,duration:travel/2,ease:'sine.inOut'},t);score.fromTo(next,{scale:.94},{scale:1,duration:travel,ease:'sine.inOut'},t)}
const style=getComputedStyle(next);score.to(document.body,{'--bg':style.getPropertyValue('--paper').trim(),'--ink':style.getPropertyValue('--letter').trim(),duration:travel,ease:'none'},t);t+=travel}
});score.to({},{duration:.5},t);score.eventCallback('onUpdate',()=>{let id=places[0].id;for(const p of places)if(score.time()>=p.start-.7)id=p.id;if(current!==id){current=id;ui.update(id)}});trigger=ScrollTrigger.create({id:'atlas',trigger:journey,pin:windowEl,start:'top top',end:()=>'+='+Math.round(innerHeight*(innerWidth<800?16:19)),animation:score,scrub:.55,invalidateOnRefresh:true,anticipatePin:1,onEnter:()=>ui.update(current),onLeaveBack:()=>ui.update('inicio')});ui.update(current);
},journey);ScrollTrigger.refresh()}
function clear(){if(layout)ScrollTrigger.removeEventListener('refreshInit',layout);layout=null;ctx?.revert();ctx=null;score=null;trigger=null;document.body.classList.remove('animated');document.body.classList.add('static');leaves.forEach(l=>{l.inert=false;l.removeAttribute('aria-hidden')});ui.update(current)}
function go(id){if(id==='inicio'){window.scrollTo({top:0,behavior:'smooth'});return}if(!trigger){document.getElementById(id)?.scrollIntoView();return}const label=score.labels[id];if(label!==undefined)window.scrollTo({top:trigger.start+(trigger.end-trigger.start)*label/score.duration(),behavior:'smooth'})}
window.Journey={go,setReduced(value){if(value){clear();document.getElementById(current)?.scrollIntoView()}else{compose();go(current)}}};if(ui.reduced())clear();else compose();Promise.all([...document.images].map(img=>img.decode?.().catch(()=>{}))).then(()=>ScrollTrigger.refresh());document.fonts.ready.then(()=>ScrollTrigger.refresh());if(location.hash)setTimeout(()=>go(location.hash.slice(1)),250);
})();
