/* Un seul plan de montage: les panneaux entiers partagent les sept raccords. */
(()=>{'use strict';const ui=window.ExperienceUI;const panels=[...document.querySelectorAll('#screen>.panel')];const screen=document.getElementById('screen'),journey=document.getElementById('journey');let context=null,tl=null,st=null,activeId='puerta',records=[];
if(!window.gsap||!window.ScrollTrigger){document.body.classList.add('static');document.querySelector('.current').textContent='Lectura sin animaciones';return}gsap.registerPlugin(ScrollTrigger);
const night=document.body.classList.contains('nocturno');const backgrounds=night?['#211e1a','#191d1c','#29221d','#1d2328','#18251f','#292825','#1a252b','#171f24']:['#d9cbb7','#252621','#e8d9c5','#272c2c','#bdcbb6','#e9e3d5','#b9cbd0','#222e32'];const inks=night?panels.map(()=>'#ece7de'):['#34362e','#eee7da','#46372e','#ece4d8','#293e31','#363833','#293b43','#e6e5dc'];panels.forEach((p,i)=>{p.style.setProperty('--panel-bg',backgrounds[i]);p.style.setProperty('--panel-ink',inks[i])});
const duration=[2.5,3.1,2.8,3.2,2.6,3.4,2.8,3.2];
function chapter(p,i,start){const q=s=>p.querySelector(s),qa=s=>p.querySelectorAll(s);const at=x=>start+x;
 // Les légendes restent stables après leur entrée. Chaque bloc a son écriture.
 if(i===0){tl.fromTo(q('.portal-window'),{scale:.78,clipPath:'inset(0% 0% 0% 0% round 48% 48% 0% 0%)'},{scale:1.13,duration:1.5,ease:'power2.inOut'},at(0));tl.fromTo(q('.portal-title'),{autoAlpha:0,y:30},{autoAlpha:1,y:0,duration:.6},at(.1));tl.fromTo(q('.portal-copy'),{autoAlpha:0,x:25},{autoAlpha:1,x:0,duration:.65},at(1.1));}
 if(i===1){tl.fromTo(q('.wall-track'),{xPercent:0},{xPercent:-25,duration:3,ease:'sine.inOut'},at(0));qa('.wall-notes p').forEach((n,k)=>{gsap.set(n,{autoAlpha:0});tl.to(n,{autoAlpha:1,y:0,duration:.32},at(.35+k*.85));if(k<2)tl.to(n,{autoAlpha:0,y:-12,duration:.3},at(1+k*.85))});tl.fromTo(q('.wall-title'),{x:30,autoAlpha:0},{x:0,autoAlpha:1,duration:.5},at(0));}
 if(i===2){tl.fromTo(q('.plaza-main'),{clipPath:'inset(0% 100% 0% 0%)',scale:1.06},{clipPath:'inset(0% 0% 0% 0%)',scale:1,duration:1.1,ease:'power2.inOut'},at(0));tl.fromTo(q('.plaza-detail'),{y:100,rotation:4,autoAlpha:0},{y:0,rotation:0,autoAlpha:1,duration:.9},at(.9));tl.fromTo(q('.plaza-copy'),{autoAlpha:0,y:18},{autoAlpha:1,y:0,duration:.6},at(1.45));tl.fromTo(q('.plaza-word'),{x:-30},{x:25,duration:2.8,ease:'none'},at(0));}
 if(i===3){tl.fromTo(q('.clock-building'),{autoAlpha:1,scale:1},{autoAlpha:.08,scale:1.12,duration:1.0},at(.55));tl.fromTo(q('.mayorga'),{autoAlpha:0,scale:.28},{autoAlpha:1,scale:1,duration:1.1,ease:'power2.inOut'},at(.65));tl.fromTo(q('.clock-title'),{autoAlpha:0,y:25},{autoAlpha:1,y:0,duration:.6},at(1.35));tl.fromTo(q('.clock-copy'),{autoAlpha:0},{autoAlpha:1,duration:.5},at(1.7));tl.fromTo(q('.clock-orbit'),{rotation:-25},{rotation:40,duration:3.2,ease:'none'},at(0));}
 if(i===4){tl.fromTo(q('.garden-window'),{clipPath:'inset(8% 12% 8% 12%)'},{clipPath:'inset(0% 0% 0% 0%)',duration:1.7,ease:'sine.inOut'},at(0));tl.fromTo(q('.garden-window img'),{scale:1.14,y:15},{scale:1,y:-6,duration:2.6,ease:'sine.inOut'},at(0));tl.fromTo(q('.garden-heading'),{autoAlpha:0,y:30},{autoAlpha:1,y:0,duration:.9},at(.1));tl.fromTo(q('.garden-bottom'),{autoAlpha:0},{autoAlpha:1,duration:.8},at(1.2));}
 if(i===5){tl.fromTo(q('.cathedral-title'),{autoAlpha:1,y:0},{autoAlpha:0,y:-45,duration:.6},at(.5));tl.fromTo(q('.cathedral-model'),{autoAlpha:0,yPercent:85,scale:.9},{autoAlpha:1,yPercent:0,scale:1,duration:1.25,ease:'power2.inOut'},at(.35));tl.to(q('.cathedral-model'),{autoAlpha:0,xPercent:-12,duration:.6},at(1.9));tl.fromTo(q('.cathedral-detail'),{clipPath:'inset(0% 100% 0% 0%)'},{clipPath:'inset(0% 0% 0% 0%)',duration:.75},at(1.9));tl.fromTo(q('.cathedral-copy'),{autoAlpha:0,y:25},{autoAlpha:1,y:0,duration:.6},at(2.35));}
 if(i===6){tl.fromTo(qa('.aqueduct-words>*'),{autoAlpha:0,y:30},{autoAlpha:1,y:0,duration:.55,stagger:.22},at(0));tl.fromTo(q('.aqueduct-photo'),{clipPath:'inset(100% 0% 0% 0%)'},{clipPath:'inset(0% 0% 0% 0%)',duration:1.1,ease:'power2.inOut'},at(.6));tl.fromTo(q('.aqueduct-photo img'),{scale:1.15,xPercent:3},{scale:1.04,xPercent:-2,duration:2.2},at(.5));tl.fromTo(q('.aqueduct-copy'),{autoAlpha:0,y:20},{autoAlpha:1,y:0,duration:.6},at(1.75));gsap.set(q('.arc-line'),{opacity:0});}
 if(i===7){tl.fromTo(q('.monument'),{clipPath:'inset(0% 0% 100% 0%)'},{clipPath:'inset(0% 0% 0% 0%)',duration:1.1},at(0));tl.fromTo(q('.ending-copy'),{autoAlpha:0,y:30},{autoAlpha:1,y:0,duration:.7},at(.6));tl.fromTo(qa('.ripples i'),{scale:.65,autoAlpha:0},{scale:1.15,autoAlpha:.35,duration:2,stagger:.15,ease:'sine.out'},at(.4));tl.fromTo(q('.last-line'),{autoAlpha:0,y:20},{autoAlpha:1,y:0,duration:.9},at(1.8));}
}
function join(a,b,i,t){const d=1.55;tl.set(b,{autoAlpha:1},t); // Both complete panels coexist during each hand-off.
 if(i===0||i===5){tl.fromTo(b,{xPercent:100},{xPercent:0,duration:d,ease:'power2.inOut'},t);tl.to(a,{xPercent:-100,duration:d,ease:'power2.inOut'},t)}
 else if(i===1){tl.fromTo(b,{xPercent:36,yPercent:100},{xPercent:0,yPercent:0,duration:d,ease:'power2.inOut'},t);tl.to(a,{xPercent:-36,yPercent:-100,duration:d,ease:'power2.inOut'},t)}
 else if(i===2){tl.fromTo(b,{scale:.55,clipPath:'circle(0% at 70% 43%)'},{scale:1,clipPath:'circle(145% at 70% 43%)',duration:d,ease:'power2.inOut'},t);tl.to(a,{scale:1.3,xPercent:-10,autoAlpha:0,duration:d,ease:'power2.inOut'},t)}
 else if(i===3){tl.fromTo(b,{clipPath:'inset(0% 0% 100% 0%)',yPercent:-12},{clipPath:'inset(0% 0% 0% 0%)',yPercent:0,duration:d,ease:'power2.inOut'},t);tl.to(a,{yPercent:25,scale:.94,duration:d,ease:'power2.inOut'},t)}
 else if(i===4){tl.fromTo(b,{yPercent:100},{yPercent:0,duration:d,ease:'power2.inOut'},t);tl.to(a,{yPercent:-100,duration:d,ease:'power2.inOut'},t)}
 else{tl.fromTo(b,{xPercent:-100,yPercent:35},{xPercent:0,yPercent:0,duration:d,ease:'power2.inOut'},t);tl.to(a,{xPercent:65,yPercent:-35,scale:.9,autoAlpha:0,duration:d,ease:'power2.inOut'},t)}
 tl.set(a,{autoAlpha:0},t+d);tl.to(document.body,{'--bg':backgrounds[i+1],'--ink':inks[i+1],duration:d,ease:'none'},t);return d;
}
function build(){document.body.classList.remove('static');document.body.classList.add('animated');records=[];context=gsap.context(()=>{gsap.set(panels,{autoAlpha:0,xPercent:0,yPercent:0,scale:1});gsap.set(panels[0],{autoAlpha:1});gsap.set(document.body,{'--bg':night?'#151a1c':'#e5dfd2','--ink':night?'#ebe7df':'#30382f'});tl=gsap.timeline({defaults:{ease:'power2.out'},paused:true});let time=0;panels.forEach((p,i)=>{tl.addLabel(p.id,time+.85);records.push({id:p.id,time});chapter(p,i,time);time+=duration[i]+.45;if(i<panels.length-1)time+=join(p,panels[i+1],i,time)});tl.to({}, {duration:.55},time);tl.eventCallback('onUpdate',()=>{let id=records[0].id;for(const r of records)if(tl.time()>=r.time-.65)id=r.id;if(id!==activeId){activeId=id;ui.update(id)}});st=ScrollTrigger.create({id:'encuentros',trigger:journey,pin:screen,start:'top top',end:()=>'+='+Math.round(innerHeight*(innerWidth<800?15:18)),animation:tl,scrub:.5,invalidateOnRefresh:true,anticipatePin:1,onUpdate(){let id=records[0].id;for(const r of records)if(tl.time()>=r.time-.65)id=r.id;if(id!==activeId){activeId=id;ui.update(id)}},onEnter:()=>ui.update(activeId),onLeaveBack:()=>ui.update('inicio')});ui.update(activeId)},journey);ScrollTrigger.refresh();}
function destroy(){context?.revert();context=null;st=null;tl=null;document.body.classList.remove('animated');document.body.classList.add('static');panels.forEach(p=>{p.inert=false;p.removeAttribute('aria-hidden')});ui.update(activeId)}
function go(id){if(id==='inicio'){window.scrollTo({top:0,behavior:'smooth'});return}if(!st||tl.labels[id]===undefined){document.getElementById(id)?.scrollIntoView();return}window.scrollTo({top:st.start+(tl.labels[id]/tl.duration())*(st.end-st.start),behavior:'smooth'})}
window.Journey={go,setReduced(value){const old=activeId;if(value){destroy();document.getElementById(old)?.scrollIntoView()}else{build();go(old)}}};
if(ui.reduced())destroy();else build();Promise.all([...document.images].map(img=>img.decode?.().catch(()=>{}))).then(()=>ScrollTrigger.refresh());document.fonts.ready.then(()=>ScrollTrigger.refresh());if(location.hash)setTimeout(()=>go(location.hash.slice(1)),250);
})();
