/* Controles comunes. La composición y sus animaciones pertenecen a cada motor. */
(()=>{'use strict';
const labels=['Puerta del Sol','La muralla','Plaza Mayor','Ayuntamiento y Mayorga','Parque de los Pinos','La catedral','El acueducto','Monumento y fuente'];
const ids=['puerta','muralla','plaza','ayuntamiento','parque','catedral','acueducto','monumento'];
const texts=['Antes de conocer una ciudad, atravesamos una sombra. El arco recorta un fragmento de luz y vuelve especial un gesto cotidiano: pasar. La historia comienza entre llegar y entrar.','La mirada encuentra una junta, la curva de un torreón y una superficie que cambia con la luz. La muralla permanece; cada paseo descubre algo distinto.','Ventanas y soportales miran hacia un espacio compartido. La plaza también se cuenta a través de una conversación, una espera y un encuentro.','La fachada presenta el conjunto. Más arriba, el Abuelo Mayorga da un rostro al tiempo y convierte la arquitectura en una presencia familiar.','La ciudad continúa entre los árboles, pero cambia de voz. Entrada, setos y pinos forman un refugio donde concederle tiempo al paseo.','Primero llega la escala. Después, relieves, aristas y sombras. La arquitectura monumental se vuelve cercana cuando la mirada encuentra un detalle.','Piedra, intervalo, cielo. La repetición de los arcos conduce la mirada. El vacío participa de la arquitectura tanto como la materia.','La figura y el pedestal permanecen. El agua propone otra forma de habitar el tiempo: cambiar sin abandonar el lugar. El recorrido termina y la ciudad sigue abierta.'];
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];let focusBefore=null;const media=matchMedia('(prefers-reduced-motion: reduce)');let reduced=media.matches;
for(const [i,id]of ids.entries()){for(const nav of [$('#rail'),$('#index nav')]){const a=document.createElement('a');a.href='#'+id;a.innerHTML=`<small>${String(i+1).padStart(2,'0')}</small><span>${labels[i]}</span>`;a.dataset.chapter=id;nav.append(a)}}
function open(d){focusBefore=document.activeElement;d.showModal();document.body.style.overflow='hidden'}function close(d){d.close();document.body.style.overflow='';focusBefore?.focus({preventScroll:true})}
$('#open-index').onclick=()=>open($('#index'));$$('dialog .close').forEach(b=>b.onclick=()=>close(b.closest('dialog')));$$('dialog').forEach(d=>d.addEventListener('cancel',e=>{e.preventDefault();close(d)}));
$$('[data-story]').forEach(b=>b.onclick=()=>{let i=ids.indexOf(b.dataset.story);$('#reader h2').textContent=labels[i];$('#reader .text').textContent=texts[i];open($('#reader'))});
function target(id){if($('#index').open)close($('#index'));if(window.Journey?.go&&!reduced)window.Journey.go(id);else document.getElementById(id)?.scrollIntoView({behavior:'auto'});history.replaceState(null,'','#'+id)}
$$('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{const id=a.getAttribute('href').slice(1);if(!document.getElementById(id))return;e.preventDefault();target(id)}));
function indicator(){const b=$('#motion');b.textContent=reduced?'○':'◉';b.setAttribute('aria-pressed',String(!reduced));b.setAttribute('aria-label',reduced?'Activar movimiento':'Desactivar movimiento')}
$('#motion').onclick=()=>{reduced=!reduced;indicator();window.Journey?.setReduced(reduced)};media.addEventListener('change',e=>{reduced=e.matches;indicator();window.Journey?.setReduced(reduced)});indicator();
window.ExperienceUI={ids,labels,reduced:()=>reduced,update(id){const n=ids.indexOf(id);$$('#rail a').forEach(a=>{const selected=a.dataset.chapter===id;a.setAttribute('aria-current',selected?'location':'false')});const title=n<0?'El comienzo':`${String(n+1).padStart(2,'0')} · ${labels[n]}`;$('.current').textContent=title;$('.chapter-status').textContent=title;for(const panel of $$('.panel,.leaf')){const isCurrent=panel.id===id;if(document.body.classList.contains('animated')){panel.inert=!isCurrent;panel.setAttribute('aria-hidden',String(!isCurrent))}else{panel.inert=false;panel.removeAttribute('aria-hidden')}}}};
addEventListener('scroll',()=>{if(document.body.classList.contains('animated'))return;const list=[...document.querySelectorAll('.panel,.leaf')];let found=null;for(const el of list)if(el.getBoundingClientRect().top<innerHeight*.45)found=el;if(found)window.ExperienceUI.update(found.id)},{passive:true});
// Canvas: únicamente partículas ambientales; la navegación pertenece a ScrollTrigger.
const canvas=$('#particulas');if(canvas){const ctx=canvas.getContext('2d');let w,h;function size(){w=innerWidth;h=innerHeight;const d=Math.min(devicePixelRatio||1,2);canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0)}size();addEventListener('resize',size);let last=0;const points=Array.from({length:28},(_,i)=>({x:i*.618%1,y:i*.381%1,r:.5+i%3*.4}));function draw(t){requestAnimationFrame(draw);if(t-last<45||document.hidden)return;last=t;ctx.clearRect(0,0,w,h);if(reduced)return;const id=document.querySelector('#rail [aria-current="location"]')?.dataset.chapter;if(!['parque','monumento'].includes(id))return;ctx.fillStyle=id==='parque'?'#d9e5af':'#b6d8de';points.forEach((p,i)=>{ctx.globalAlpha=.1+.14*Math.sin(t*.0006+i)**2;ctx.beginPath();ctx.arc(p.x*w+Math.sin(i+t*.0002)*12,((p.y*h-t*.006)%h+h)%h,p.r,0,Math.PI*2);ctx.fill()})}requestAnimationFrame(draw)}
})();
